Change to Blockchain Commons CLA until W3C CCG approval
BlockchainCommons/did-method-onion pull request #6
Opened 2020-12-11 22:22 UTC by ChristopherA

I was reminded this week that as this spec is not approved as a work item under the W3C CCG, we coudn't use the W3C CLA and License.

This PR changes the CLA and LICENSE so that when this effort is approved, Blockchain Commons has the rights such that we can assign it to the W3C. Our CLA was specifically designed to support this, and requires all contributors to submit a GPG-signed CLA.

I have also included my own signed CLA in /CLAs-signed as a GPG-signed git commit. @OR13 should also submit his GPG-signed CLA.md as well as a GPG-signed commit in a PR.

2020-12-11 22:26 UTC, ChristopherA commented
@OR13 In your CLA PR, you should also add yourself to the [credits list](https://github.com/BlockchainCommons/did-method-onion#credits) with your GPG key.

2020-12-14 20:33 UTC, OR13 requested changes
@ChristopherA can you make signing the CLA a one liner? I hate CLAs, and this process seems to make them even worse...

I originally contributed to this based on the assumption that my contribution would be covered by the CCG License, even without it being approved yet, hence the respec included it.

2020-12-14 20:33 UTC, OR13 commented
I would also accept a CLA bot github action

2020-12-14 20:55 UTC, ChristopherA commented
> @ChristopherA can you make signing the CLA a one liner? I hate CLAs, and this process seems to make them even worse...

There is a one-liner at the bottom of CLA for signing it. 

> I originally contributed to this based on the assumption that my contribution would be covered by the CCG License, even without it being approved yet, hence the respec included it.

Understood. But until it is accepted we are in catch-22.

2020-12-14 20:58 UTC, OR13 commented
I see `gpg --armor --clearsign --output CLA.YOURGITHUBNAME.YOURGPGFINGERPRINT.asc CLA.md` I can try and add mine, lets merge your first.

2020-12-14 20:59 UTC, OR13 approved these changes

2020-12-14 20:59 UTC, merged